import React, { useState, useEffect } from 'react';
import { Sidebar } from './components/Sidebar';
import { LessonGenerator } from './components/LessonGenerator';
import { HomeReviewGenerator } from './components/HomeReviewGenerator';
import { Dashboard } from './components/Dashboard';
import { GeneratedLessonPlan } from './types';

// Mock data to pre-populate dashboard if empty
const MOCK_PLANS: GeneratedLessonPlan[] = [
    {
        id: 'mock-1',
        generalData: {
            subject: 'Matemáticas',
            grade: '5to Grado',
            unit: 'Geometría Básica',
            achievementIndicator: 'Identifica y clasifica triángulos según sus lados.',
            contentConceptual: 'Clasificación de Triángulos'
        },
        faithIntegration: {
            objective: 'Reconocer la diversidad en la creación de Dios a través de las formas geométricas.',
            bibleVerse: 'Salmos 139:14',
            spiritualConcept: 'Diversidad y Orden'
        },
        sequence: [],
        evaluation: { qualitative: [], quantitative: [] },
        resources: []
    },
    {
        id: 'mock-2',
        generalData: {
            subject: 'Ciencias Naturales',
            grade: '4th Grado',
            unit: 'Seres Vivos',
            achievementIndicator: 'Describe las partes de la planta y sus funciones.',
            contentConceptual: 'La Fotosíntesis'
        },
        faithIntegration: {
            objective: 'Apreciar el sustento de Dios para la vida.',
            bibleVerse: 'Génesis 1:11',
            spiritualConcept: 'Providencia Divina'
        },
        sequence: [],
        evaluation: { qualitative: [], quantitative: [] },
        resources: []
    }
];

export default function App() {
  const [currentView, setCurrentView] = useState<'dashboard' | 'create' | 'saved' | 'review'>('dashboard');
  const [plans, setPlans] = useState<GeneratedLessonPlan[]>(MOCK_PLANS);
  // Track the specific plan generated by the user in this session to auto-fill review
  const [lastGeneratedPlan, setLastGeneratedPlan] = useState<GeneratedLessonPlan | null>(null);

  const handlePlanGenerated = (newPlan: GeneratedLessonPlan) => {
    setPlans(prev => [newPlan, ...prev]);
    setLastGeneratedPlan(newPlan);
    // Optional: Auto-switch to a detail view or stay to print
  };

  const renderContent = () => {
    switch (currentView) {
      case 'dashboard':
        return <Dashboard savedPlans={plans} />;
      case 'create':
        return <LessonGenerator onPlanGenerated={handlePlanGenerated} />;
      case 'review':
        return <HomeReviewGenerator linkedPlan={lastGeneratedPlan} />;
      case 'saved':
        return (
            <div className="bg-white rounded-2xl p-8 shadow-sm text-center">
                <h2 className="text-2xl font-bold text-slate-800">Mis Planes Guardados</h2>
                <p className="text-slate-500 mt-2">Funcionalidad completa en desarrollo. Ver Dashboard para resumen.</p>
                <button onClick={() => setCurrentView('dashboard')} className="mt-4 text-indigo-600 hover:underline">Volver al Dashboard</button>
            </div>
        );
      default:
        return <Dashboard savedPlans={plans} />;
    }
  };

  const getTitle = () => {
      switch(currentView) {
          case 'create': return 'Crear Nuevo Plan';
          case 'review': return 'Repaso para WhatsApp';
          case 'dashboard': return 'Dashboard';
          case 'saved': return 'Mis Planes';
          default: return 'Plan Ultra';
      }
  }

  return (
    <div className="min-h-screen bg-slate-50 flex font-sans text-slate-900">
      <Sidebar currentView={currentView} setCurrentView={setCurrentView} />
      
      <main className="flex-1 ml-64 p-8 overflow-y-auto h-screen">
        <header className="flex justify-between items-center mb-8">
          <div>
             <h1 className="text-2xl font-bold text-slate-900 capitalize">
                {getTitle()}
             </h1>
             <p className="text-slate-500 text-sm">
                Sistema de Planificación Educativa Adventista de Nicaragua
             </p>
          </div>
          <div className="flex items-center space-x-4">
             <div className="bg-white px-4 py-2 rounded-full border border-slate-200 shadow-sm flex items-center space-x-2">
                <div className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></div>
                <span className="text-xs font-medium text-slate-600">Sistema Operativo</span>
             </div>
             <div className="h-10 w-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-700 font-bold border border-indigo-200">
                P
             </div>
          </div>
        </header>

        {renderContent()}
      </main>
    </div>
  );
}